---
- name: Add Nimble Streamer repository (Centos 7)
  yum_repository: 
    name: nimble 
    description: Nimble Streamer repository 
    baseurl: http://nimblestreamer.com/centos/7/$basearch 
    enabled: yes
    gpgcheck: yes
    gpgkey: http://nimblestreamer.com/gpg.key
    
- name: Install the latest version of Nimble Streamer
  yum:
    name: nimble
    state: latest
    
- name: Install the latest version of Nimble Transcoder
  yum:
    name: nimble-transcoder
    state: latest
  when: nimble_transcoder
  
  
  
- name: Enable service nimble and ensure it is not masked
  systemd:
    name: nimble
    enabled: yes
    masked: no

- name: Make sure nimble service is running
  systemd: 
    name: httpd
    state: started 