---
- name: Add Nimble Streamer repository (Centos 7)
  yum_repository: 
    name: nimble 
    description: Nimble Streamer repository 
    baseurl: http://nimblestreamer.com/centos/7/$basearch 
    enabled: yes
    gpgcheck: yes
    gpgkey: http://nimblestreamer.com/gpg.key
    
- name: Install Nimble Streamer
  yum:
    name: "nimble-{{nimble_streamer_version|default(3)}}*"
    state: present
    
- name: Install Nimble Transcoder
  yum:
    name: nimble-transcoder
    state: present
  when: nimble_transcoder
  
- include: config.yml
  tags:
    - config
  
- name: Enable service nimble and ensure it is not masked
  systemd:
    name: nimble
    enabled: yes
    masked: no

- name: Make sure nimble service is running
  systemd: 
    name: nimble
    state: started 
    
# TODO: Reload if "Install Nimble Streamer" task installed a new version